USE [master]
GO

/****** Object:  Database [MyOrder]    Script Date: 16/11/2022 21:27:13 ******/
CREATE DATABASE [MyOrder]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MyOrder', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MyOrder.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MyOrder_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MyOrder_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MyOrder].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MyOrder] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MyOrder] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MyOrder] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MyOrder] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MyOrder] SET ARITHABORT OFF 
GO

ALTER DATABASE [MyOrder] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MyOrder] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MyOrder] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MyOrder] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MyOrder] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MyOrder] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MyOrder] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MyOrder] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MyOrder] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MyOrder] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MyOrder] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MyOrder] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MyOrder] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MyOrder] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MyOrder] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MyOrder] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MyOrder] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MyOrder] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MyOrder] SET  MULTI_USER 
GO

ALTER DATABASE [MyOrder] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MyOrder] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MyOrder] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MyOrder] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MyOrder] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MyOrder] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [MyOrder] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MyOrder] SET  READ_WRITE 
GO

